CallBy.dfy(26,2): Error: assertion could not be proved
CallBy.dfy(32,2): Error: assertion could not be proved
CallBy.dfy(39,2): Error: assertion could not be proved
CallBy.dfy(50,2): Error: assertion could not be proved
CallBy.dfy(56,2): Error: assertion could not be proved
CallBy.dfy(66,2): Error: assertion could not be proved

Dafny program verifier finished with 4 verified, 6 errors
